# read train dataset and test datasetï¼Œcategorical features preprocessing

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
#read data from dataset
data = pd.read_csv(r"./traindata.csv")
testdata = pd.read_csv(r"./testdata.csv")

In [3]:
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^ categorical features preprocessing  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
# author:           Kun Yan
# student number:   300259303
# data:             2021-10-03
# Python version:   3.9.7
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


# Step1: drop 3 categorical features:
#              ID, num_outbound_cmds (value=0), is_host_login (value=0)
data.drop(["ID", "num_outbound_cmds", "is_host_login"],axis=1,inplace=True)
testdata.drop(["ID", "num_outbound_cmds", "is_host_login"],axis=1,inplace=True)


# step 2: categorical features:
# OneHotEncorder() - non importance, non order
# f2 (protocol_type),f3 (service),f4(flag) -OneHotEncoder to 80 columns
def cat_trans(X,X_test):
    t = OneHotEncoder(categories='auto',handle_unknown='ignore').fit(X)

    result = t.transform(X).toarray()
    result_test = t.transform(X_test).toarray()

    X = pd.DataFrame(result)
    X.columns = t.get_feature_names_out()

    X_test = pd.DataFrame(result_test)
    X_test.columns = t.get_feature_names_out()
    return X, X_test

f_cat_org = pd.concat([data["protocol_type"],data["service"],data["flag"]],axis=1)
f_cat_test_org = pd.concat([testdata["protocol_type"],testdata["service"],testdata["flag"]],axis=1)

f_cat, f_cat_test = cat_trans(f_cat_org,f_cat_test_org)


################# drop and concat ##########
data.drop(["protocol_type", "service", "flag"],axis=1,inplace=True)
testdata.drop(["protocol_type", "service", "flag"],axis=1,inplace=True)

data_aftcat = pd.concat([data.iloc[:,0:-1],f_cat],axis=1)
data_y = data["Class"]
testdata_aftcat = pd.concat([testdata,f_cat_test],axis=1)

In [4]:
#-----------output-------------------

data_aftcat.to_csv("./1-1 5388 traindata_aftcat.csv",index=0)
data_y.to_csv("./1-1 5388 traindata_aftcat_label.csv",index=0)
data_y = pd.DataFrame(data_y)
testdata_aftcat.to_csv("./1-1 5388 testdata_aftcat.csv",index=0)

In [5]:
data_aftcat

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0,295,2584,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0,312,839,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0,1225,2451,0,0,0,28,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0,293,296,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22997,0,0,0,0,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22998,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
22999,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
23000,0,516,4,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
23001,0,305,0,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [6]:
data_y

       Class
0          0
1          0
2          1
3          0
4          0
...      ...
22997      0
22998      1
22999      1
23000      0
23001      0

[23002 rows x 1 columns]

In [7]:
testdata_aftcat

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,4,30,93,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0,52,54,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0,367,588,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0,1008,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22496,0,298,2248,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22497,281,160,599,0,0,0,2,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22498,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
22499,0,199,11107,0,0,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
22500,0,53,50,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0